version: '3.8'

services:
  cors-proxy:
    build: . # use mine: artemis00/cors-proxy-go if you want pre-built image
    container_name: cors-proxy
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - cors-proxy-network

networks:
  cors-proxy-network:
    driver: bridge
